"""empty message

Revision ID: 5dfa4e51d051
Revises: 44efc76bb2a0
Create Date: 2018-06-18 17:30:52.863557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfa4e51d051'
down_revision = '44efc76bb2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('close', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('close', 'create_time')
    # ### end Alembic commands ###
